[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cells2visium"
version = "0.0.1"
dynamic = ["dependencies"]
authors = [
  {name = "Stanislaw Makarchuk", email = "stanislaw.makarchuk@sanger.ac.uk"}
]
maintainers = [
  {name = "Stanislaw Makarchuk", email = "stanislaw.makarchuk@sanger.ac.uk"}
]
description = "Segmenting H&E images from Visium to assign each Visium spot to the number of cell, occupancy and other morphological features of cells"
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/cellgeni/cells2visium"
"Bug Tracker" = "https://github.com/cellgeni/cells2visium/issues"

[project.scripts]
cells2visium = "cells2visium.cells2visium:cli"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
